core/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'     # the app name will come handy in calling view from templates like   appname: thankyou  (like reverse )

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),    # path expects  a function
    path('thankyou/', views.ThankYouView.as_view(), name='thankyou'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('create_teacher/', views.TeacherCreateView.as_view(), name='create_teacher'),
    path('teacher_list', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('update_teacher/<int:pk>/', views.TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

core/classroom/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    name = models.CharField(max_length=60)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.name} teaches, {self.subject}"

core/classroom/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)

core/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from .forms import ContactForm
from .models import Teacher
from django.urls import reverse_lazy, reverse
# Create your views here.


# def home(request):
#     return render(request, 'classroom/home.html')


class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThankYouView(TemplateView):
    template_name = 'classroom/thankyou.html'


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # url not a template.html
    success_url = '/classroom/thankyou'   # or reverse_lazy('classroom:thankyou')  # which url to go after successful submission of forms (actual url ) not html file name
                                        # we also can not use reverse function in success_url we can use reverse_lazy instead of it

    # what to do with form
    def form_valid(self, form):
        # form.save()
        print(form.cleaned_data)   # printing form data on screen
        return super().form_valid(form)               # same as ContactForm(request, POST )


class TeacherCreateView(CreateView):
    model = Teacher       # view connected with model it will directly create form for the creation of teacher
    #model_form.html    automatically called by looking at convention
    #form.save()
    fields = '__all__'       # here you need to mention which things you want to show into forms you can change the order also by passing the list
    success_url = reverse_lazy('classroom:thankyou')


class TeacherListView(ListView):
    #teacher_list.html   # by default call this by using convention
    model = Teacher    # this by default calls the objects.all() and links to the thing
    queryset = Teacher.objects.order_by('name')     # we are overiding the default query i.e. Teacher.objects.all()
    context_object_name = "teacher_list"   # this teacher list will be passed to html template


# the purpose of detail view is to view a single instance's all fields
class TeacherDetailView(DetailView):
    #looks for teacher_detail.html
    model = Teacher
    #pk--> {{teacher}}   find teacher by primary key and send object


class TeacherUpdateView(UpdateView):
    # share model_form.html file   and then show us filled form we can make changes to that
    model = Teacher
    fields = '__all__'    # list of values to update
    success_url = reverse_lazy('classroom:teacher_list')


class TeacherDeleteView(DetailView):
    # it send form----> that has confirm delete button
    # looks for model_confirm_delete.html
    template_name = 'classroom/teacher_confirm_delete.html'
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')




core/classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
<body>
  <h1> Form View Template (contact.html) </h1>
  <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="submit">
  </form>
</body>
</html>

core/classroom/templates/classroom/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME</title>
</head>
<body>
    <h1> Welcome to home page </h1>
    <ul>
        <li>
            <a href="{% url 'classroom:thankyou' %}"> Thank you </a>
        </li>
        <li>
            <a href="{% url 'classroom:contact' %}"> Contact Form </a>
        </li>
        <li>
            <a href="{% url 'classroom:create_teacher' %}"> Create Teacher </a>
        </li>
        <li>
            <a href="{% url 'classroom:teacher_list' %}"> List Of Teachers </a>
        </li>
    </ul>
</body>
</html>

core/classroom/templates/classroom/teacher_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete teacher </title>
</head>
<body>
  <h1>Deleting Teacher</h1>
  <h2> {{teacher}} </h2>
  <h3> Are you sure you want to delete this teacher </h3>
    <form method="POST">
      {% csrf_token %}
      <input type="submit" value="Delete">
    </form>
</body>
</html>

core/classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher's details</title>
</head>
<body>
    <h1>All Details of teacher </h1>
    {{teacher}}
</body>
</html>

core/classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Creation Form</title>
</head>
<body>
    <h1> Teacher Form </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="submit">
    </form>
</body>
</html>

core/classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers List</title>
</head>
<body>
    <h1> List of all teachers </h1>
  <ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.name}} teaches {{teacher.subject}}</a>
            <ul>
                <li>
                    <a href="/classroom/update_teacher/{{teacher.id}}">    Update Info </a>
                </li>
                <li>
                    <a href="/classroom/delete_teacher/{{teacher.id}}">    Delete teacher </a>
                </li>
            </ul>
        </li>

    {% endfor %}
  </ul>
</body>
</html>

core/classroom/templates/classroom/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thank You</title>
</head>
<body>
    <h1>Thank you for visiting our page </h1>
</body>
</html>